name: CI - BookStore

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: {}
  schedule:
    - cron: '0 12 * * 4'

concurrency:
  group: ci-bookstore
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Dar permissão ao gradlew
        run: chmod +x gradlew

      - name: Rodar testes
        run: ./gradlew --no-daemon clean cucumber -Dfile.encoding=UTF-8

      - name: Upload do relatório Extent
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-report
          path: build/reports/extent-report/
          if-no-files-found: warn