name: CI - BookStore

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - run: chmod +x gradlew
      - run: ./gradlew --no-daemon clean cucumber -Dfile.encoding=UTF-8

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: extent-report
          path: build/reports/extent-report/
          if-no-files-found: warn